I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/intro.rpy", line 5, in script
    "Rozpoczynasz swoją przygodę jako ludzki kupiec z leżącej na północy Federacji Lyvsik"
TypeError: 'bool' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/intro.rpy", line 5, in script
    "Rozpoczynasz swoją przygodę jako ludzki kupiec z leżącej na północy Federacji Lyvsik"
  File "C:\renpy-7.2.2-sdk\renpy\ast.py", line 694, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\renpy-7.2.2-sdk\renpy\exports.py", line 1322, in say
    who(what, *args, **kwargs)
TypeError: 'bool' object is not callable

Windows-8-6.2.9200
Ren'Py 7.2.2.491
Road to Urdinas_v0.1 0.1
Sun May 05 18:56:30 2019
